# Generated by Django 4.1.1 on 2023-02-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("epz5", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="faq_Page",
        ),
    ]
