# Generated by Django 4.1.1 on 2023-02-03 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Home_Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("league", models.CharField(max_length=100)),
                ("home_team", models.CharField(max_length=100)),
                ("away_team", models.CharField(max_length=100)),
                ("tip", models.CharField(max_length=100)),
                ("tip_odd", models.DecimalField(decimal_places=10, max_digits=20)),
                ("result", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
            ],
            options={
                "ordering": ("league",),
            },
        ),
    ]
