# Generated by Django 4.1.1 on 2023-02-03 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("epz1", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="home_page",
            options={"ordering": ("league",)},
        ),
        migrations.RemoveField(
            model_name="home_page",
            name="match_dat",
        ),
        migrations.RemoveField(
            model_name="home_page",
            name="match_time",
        ),
        migrations.AddField(
            model_name="home_page",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="home_page",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="home_page",
            name="tip_odd",
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
