# Generated by Django 4.1.1 on 2023-02-08 00:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("epz1", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="home_page",
            options={"ordering": ("-date_time",)},
        ),
        migrations.AddField(
            model_name="home_page",
            name="pub_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
