# Generated by Django 4.1.1 on 2023-02-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epz1", "0003_ipmodel_home_page_vote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home_page",
            name="vote",
        ),
        migrations.AddField(
            model_name="home_page",
            name="vote_dislike",
            field=models.ManyToManyField(
                blank=True, related_name="vote_dislikes", to="epz1.ipmodel"
            ),
        ),
        migrations.AddField(
            model_name="home_page",
            name="vote_like",
            field=models.ManyToManyField(
                blank=True, related_name="vote_likes", to="epz1.ipmodel"
            ),
        ),
    ]
